version: '3.3'

services: 
  position-collector:
    image: christianseki/position-collector:latest
    ports:
      - "4444:4444"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    environment:
      - STUDENTS_PICKUP_QUEUE_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - REDIS_URI=redis://redis-gps
      - REDIS_HOST=redis-gps
    networks:
      - public
  redis-gps:
    image: redis:7
    volumes:
      - redis-gps-data:/data
    command: redis-server --maxmemory-policy allkeys-lru
    ports:
      - "6379"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    networks:
      - public

networks:
  public:
    driver: overlay
    external: true

volumes:
  redis-data:
    driver: local